baseURL = 'https://turtlekey.github.io/'
languageCode = 'en-us'
publishDir = 'docs'

theme = "yangyin"
DefaultContentLanguage = "cn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "turtlekey"
  homepage = ""


[params]
mainSections = ["posts"]
headTitle = "After the Gold Rush"
description = 'the long horns are gone, and so are the drovers.' 
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
[[params.socials]]
name = "About Me"
link = "/about"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []
